services:
  db:
    image: postgres:15
    container_name: tienda_db
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: tienda_backend
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: tienda_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data: